name: Hardware Build Test

# No point on running this on pushes to master
# as we already dispatch a run job for that event
on:
  pull_request:
    branches: 'master'

jobs:
  run_benchmark:
    runs-on: self-hosted
    name: Hardware Build Test
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libfontconfig-dev

      - name: Install EJ dispatcher tool
        run: |
          cargo install ejlv

      - name: Dispatch job
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            REPO_URL="${{ github.event.pull_request.head.repo.clone_url }}"
            COMMIT_REF="${{ github.event.pull_request.head.sha }}"
          else
            REPO_URL="${{ github.server_url }}/${{ github.repository }}"
            COMMIT_REF="${{ github.sha }}"
          fi

          set +e
          ejlv dispatch-build \
            --socket /ejd/ejd.sock \
            --commit-hash $COMMIT_REF \
            --remote-url $REPO_URL \
            --seconds 1800

          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 0 ]; then
            exit 0
          fi
          
          echo "ejlv returned exit code " $EXIT_CODE ", cancelling workflow"
          echo "SHOULD_CANCEL=true" >> $GITHUB_ENV
          exit 0

      - name: Cancel workflow if needed
        if: env.SHOULD_CANCEL == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
